---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04
    steps:
      - name: logging to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v3
      - name: test
        run: docker-compose run --rm app sh -c "python manage.py test" 